TARGET = tinybar_v2

CPU_FREQ = 16000000

XRAM_SIZE = 0x0200

XRAM_LOC = 0x0000

CODE_SIZE = 0x2800

C_FILES = \
	main.c \
	bitbang.c \
	../../include/debug.c

ASM_FILES = \
	bitbang_asm.asm

pre-flash:
	

include ../Makefile.include
